import Link from 'next/link'
import { Compass } from 'lucide-react'

export function SiteFooter() {
  return (
    <footer className="border-t border-border/70 bg-secondary/40">
      <div className="mx-auto flex max-w-6xl flex-col gap-4 px-4 py-8 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-center gap-2">
          <span className="flex size-7 items-center justify-center rounded-md bg-primary text-primary-foreground">
            <Compass className="size-4" aria-hidden="true" />
          </span>
          <span className="font-serif text-lg font-semibold">Wayfare</span>
        </div>
        <p className="max-w-md text-sm text-muted-foreground text-pretty">
          Travel that honors the people and traditions behind every place.
          Recommendations and stories are generated by AI to spark discovery —
          always verify details with local sources before you go.
        </p>
        <nav className="flex gap-4 text-sm text-muted-foreground">
          <Link href="/" className="hover:text-foreground">
            Discover
          </Link>
          <Link href="/recommend" className="hover:text-foreground">
            For You
          </Link>
          <Link href="/companion" className="hover:text-foreground">
            Companion
          </Link>
        </nav>
      </div>
    </footer>
  )
}
